query GetMain {
    page(id: "/", idType: URI) {
        title
        aboutBlock {
            about {
                text
                title
                image {
                    sourceUrl
                }
                link {
                    ... on Page {
                        uri
                    }
                }
            }
        }
        services {
            serviceTitle
            serviceList {
                icon
                text
                title
                link {
                    ... on Expertise {
                        uri
                    }
                }
            }
        }
        seo {
            title
            metaDesc
        }
    }
}
