{
  projects {
    nodes {
      title
      excerpt
      uri
      featuredImage {
        node {
          sourceUrl
        }
      }
    }
  }
  page: pageBy(uri: "our-works") {
    seo {
      title
      metaDesc
    }
  }
}
